language: go
sudo: required

services:
  - docker

go:
  - tip
  - "1.9"
install:
  - go get -d -v ./...
  - go build
script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/fsouza/go-dockerclient
  - go get github.com/tiago4orion/conjure
  - go get golang.org/x/tools/cmd/cover
  - hack/check.sh
#  - goveralls -coverprofile=coverage.txt -service=travis-ci
before_install:
  - sudo pip install codecov
after_success:
  codecov
notifications:
  email:
    - tiago.natel@neoway.com.br
